name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2️⃣ Use a modern Node.js so Next.js understands ?? / ?.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # LTS ≥ 18 also works
          cache: npm # caches node_modules automatically

      # 3️⃣ Cache Next.js compilation artifacts (speeds incremental builds)
      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      # 4️⃣ Install deps, build, export
      - name: Install dependencies
        run: npm ci # reproducible, faster than `npm install`

      - name: Build app
        run: npm run build

      - name: Export static site
        env:
          CI: true
        run: npm run export

      # 5️⃣ Keep GitHub Pages from running Jekyll
      - name: Add .nojekyll
        run: touch out/.nojekyll

      # 6️⃣ Deploy to gh-pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.BLOG_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
